# config.py

SERIAL_PORT = "COM7"
BAUDRATE = 115200
SERIAL_TIMEOUT = 1
CONNECTION_CHECK_TIMEOUT = 3

MAVLINK_STATE_PORT = 'udpout:192.168.43.1:14552'
MAVLINK_COMMAND_PORT = 'udpout:192.168.43.1:14552'
HEARTBEAT_TIMEOUT = 5

START_BYTE = 0xAA
END_BYTE = 0x55
PACKET_SIZE = 6

MAIN_LOOP_DELAY = 0.01

DEFAULT_TAKEOFF_ALTITUDE = 50
SAFE_BATTERY_LEVEL = 20

ARM_BIT = 4
RTL_BIT = 2
MANUAL_BIT = 11
TAKEOFF_BIT = 6
EMERGENCY_BIT = 0
SYSTEM_CHECK_BIT = 8

ENABLE_PREFLIGHT_CHECKS = True
ENABLE_FAILSAFE = True
ENABLE_ARMING_CHECKS = True

STM32_RECONNECT_DELAY = 2
STM32_TIMEOUT = 3

DEBUG_MODE = True
PRINT_RAW_PACKETS = True
PRINT_SYSTEM_STATE = True