# mqtt_bridge/tests/conftest.py
"""Synthesised MAVLink frames for the framing tests.

Frames are built BY HAND here rather than with pymavlink, deliberately. The
framer's whole purpose is to be independent of the dialect, so a test corpus
generated by the dialect would not exercise the cases that matter: an unknown
msgid, a wrong CRC, a reserved incompat flag. Those cannot be produced through
the normal pymavlink encode path, which is precisely why the framer exists.

One test (test_bad_crc_interop) does use pymavlink, to demonstrate the design
rationale directly: a frame pymavlink rejects must still cross our tunnel.
"""

import sys
from pathlib import Path

import pytest

# Allow `python -m pytest` from Plugins/UAV_ and a bare `pytest` from anywhere.
_UAV_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_UAV_ROOT) not in sys.path:
    sys.path.insert(0, str(_UAV_ROOT))

from mqtt_bridge.framing import (  # noqa: E402
    CRC_LEN, HDR_V1, HDR_V2, IFLAG_SIGNED, SIG_LEN, STX_V1, STX_V2,
)


def _payload(n, seed=0):
    """n deterministic payload bytes, deliberately including 0xFD and 0xFE.

    Start bytes inside a payload must not confuse a length-driven framer. If
    they ever do, these fixtures will catch it.
    """
    if n == 0:
        return b""
    pat = bytes([0xFD, 0xFE, 0x00, 0xFF, 0xAA, 0x55])
    return bytes(((seed + i) & 0xFF) if i % 7 else pat[i % len(pat)] for i in range(n))


def make_v1(payload_len=4, seq=0, sysid=1, compid=1, msgid=0, crc=0xBEEF, seed=0):
    """A MAVLink v1 frame. Total length = 6 + payload_len + 2."""
    assert 0 <= payload_len <= 255
    body = bytes([STX_V1, payload_len, seq & 0xFF, sysid & 0xFF, compid & 0xFF, msgid & 0xFF])
    body += _payload(payload_len, seed)
    body += bytes([crc & 0xFF, (crc >> 8) & 0xFF])
    assert len(body) == HDR_V1 + payload_len + CRC_LEN
    return body


def make_v2(payload_len=4, seq=0, sysid=1, compid=1, msgid=0,
            signed=False, incompat=None, compat=0, crc=0xBEEF, seed=0):
    """A MAVLink v2 frame. Total = 10 + payload_len + 2 (+13 when signed).

    `incompat` overrides the flag byte outright, for the reserved-bit tests.
    """
    assert 0 <= payload_len <= 255
    if incompat is None:
        incompat = IFLAG_SIGNED if signed else 0
    body = bytes([
        STX_V2, payload_len, incompat & 0xFF, compat & 0xFF, seq & 0xFF,
        sysid & 0xFF, compid & 0xFF,
        msgid & 0xFF, (msgid >> 8) & 0xFF, (msgid >> 16) & 0xFF,
    ])
    body += _payload(payload_len, seed)
    body += bytes([crc & 0xFF, (crc >> 8) & 0xFF])
    if incompat & IFLAG_SIGNED:
        # linkid(1) + timestamp(6) + signature(6). Contents are never inspected
        # by the framer, only counted, so any 13 bytes exercise the arithmetic.
        body += bytes([0x01]) + bytes(range(0x10, 0x16)) + bytes(range(0x20, 0x26))
    expected = HDR_V2 + payload_len + CRC_LEN + (SIG_LEN if incompat & IFLAG_SIGNED else 0)
    assert len(body) == expected, (len(body), expected)
    return body


@pytest.fixture
def frame_corpus():
    """A varied list of individually valid frames, smallest and largest included."""
    frames = [
        make_v1(payload_len=0),                      # 8 bytes, the minimum
        make_v1(payload_len=9, msgid=0),             # HEARTBEAT-shaped v1
        make_v1(payload_len=255, seed=3),            # 263 bytes, v1 maximum
        make_v2(payload_len=0),                      # 12 bytes, v2 minimum
        make_v2(payload_len=9, msgid=0),             # HEARTBEAT-shaped v2
        make_v2(payload_len=255, seed=5),            # 267 bytes, v2 unsigned max
        make_v2(payload_len=0, signed=True),         # 25 bytes, signed minimum
        make_v2(payload_len=255, signed=True, seed=7),  # 280, the absolute max
        make_v2(payload_len=16, msgid=0xFFFFF0),     # msgid in no dialect
        make_v2(payload_len=32, msgid=385, compat=0x01),  # compat flag set (legal)
    ]
    # Repeat with varied seq/sysid so the stream is ~50 frames of mixed shapes.
    out = []
    for rep in range(5):
        for i, f in enumerate(frames):
            b = bytearray(f)
            if b[0] == STX_V1:
                b[2] = (rep * 10 + i) & 0xFF        # seq
            else:
                b[4] = (rep * 10 + i) & 0xFF        # seq
            out.append(bytes(b))
    return out


@pytest.fixture
def frame_stream(frame_corpus):
    """The corpus concatenated into one contiguous byte stream."""
    return b"".join(frame_corpus)
